repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.52.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_validate
    - id: terraform_docs
    - id: terraform_tfsec
    - id: checkov
